"""Rename serial_number to control_number

Revision ID: 619240773c53
Revises: 0ebada7e2ca0
Create Date: 2024-09-12 10:34:19.680582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '619240773c53'
down_revision = '0ebada7e2ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=255), nullable=True))
        batch_op.drop_index('serial_number')
        batch_op.create_unique_constraint(None, ['serial_number'])
        batch_op.drop_column('control_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_number', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('serial_number', ['control_number'], unique=True)
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
