"""Remove serial_number column

Revision ID: 69f4bdecfb82
Revises: 619240773c53
Create Date: 2024-09-12 11:02:24.442634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f4bdecfb82'
down_revision = '619240773c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_object', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['control_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_object', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
